# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_Week6' do
  use_frameworks!

  # Pods for SOPT_Week6
    pod 'Alamofire'
    pod 'Kanna'

end
