# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'KDCircularProgress', :git => 'https://github.com/kaandedeoglu/KDCircularProgress'
  # Pods for ChartExample

end
