# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoTutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod "PryntTrimmerView"
  # Pods for VideoTutorial

  target 'VideoTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoTutorialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
