# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LOTTIE_Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'lottie-ios'

  # Pods for LOTTIE_Example

end
