# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_Week4' do
  use_frameworks!

  # Pods for SOPT_Week4
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
end
