# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_HomeWork3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'Kingfisher'
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'SideMenu'
    pod 'KMPlaceholderTextView', '~> 1.3.0'
    pod 'IQKeyboardManagerSwift'
end
